services:
  mysql:
    image: "mysql:8.1"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: voting
      MYSQL_PASSWORD: voting
      MYSQL_DATABASE: voting
    ports:
      - "3306:3306"
#    networks:
#      - net_db_vot

  voting:
    build: .
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_USERNAME: voting
      DB_PASSWORD: voting
      DB_DATABASE: voting
    depends_on:
      - redis
      - mysql
    ports:
      - "9000:9000"
#    networks:
#      - net_vot_nginx
#      - net_db_vot

  redis:
    image: redis:4-alpine
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx.access
    ports:
      - "6379:6379"
#    networks:
#      - net_db_vot

  nginx:
    image: "nginx:alpine"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.:/var/www/html
    ports:
      - "20000:8080"
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx.access
    depends_on:
      - voting
#    networks:
#      - net_vot_nginx

#  web:
#    image: httpd
#    ports:

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:8.6.1
#    command: sysctl -w vm.max_map_count=262144
    volumes:
      - ./elastic/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic/unsecure.policy:/usr/share/elasticsearch/unsecure.policy
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.2.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

#networks:
#  net_vot_nginx:
#  net_db_vot:
