services:
  mysql:
    image: "mysql:8.1"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: voting
      MYSQL_PASSWORD: voting
      MYSQL_DATABASE: voting
    ports:
      - "3306:3306"
    networks:
      - net_db_vot

  voting:
    build: .
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_USERNAME: voting
      DB_PASSWORD: voting
      DB_DATABASE: voting
    depends_on:
      - redis
      - mysql
    ports:
      - "9000:9000"
    networks:
      - net_vot_nginx
      - net_db_vot

  redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"
    networks:
      - net_db_vot

  nginx:
    image: "nginx:alpine"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.:/var/www/html
    ports:
      - "20000:80"
    depends_on:
      - voting
    networks:
      - net_vot_nginx

networks:
  net_vot_nginx:
  net_db_vot:
